//! gettext-style i18n: po/<locale>.po compiled by build.rs into a static lookup (no runtime
//! files); msgid = the English source string; a missing entry falls back to the source.
//! Locale negotiation lives in the web layer (`lang_of`): the browser's Accept-Language (when
//! `http_accept_language` is on) else the `default_lang` CEL expression.

// Generated by build.rs: `pub static CATALOGS: &[(&str, &[(&str, &str)])]`.
include!(concat!(env!("OUT_DIR"), "/i18n_catalog.rs"));

/// Translate `msgid` into `locale` (a primary subtag like "fi"); English source on any miss.
pub fn tr(locale: &str, msgid: &str) -> String {
    lookup(CATALOGS, locale, msgid).unwrap_or_else(|| msgid.to_string())
}

/// The browser's most-preferred locale we actually have a catalog for: primary subtags only,
/// q-values ignored (header order is preference enough). `None` when there's no header or no
/// match — the caller (`lang_of`) decides the fallback.
pub fn best_locale(accept_language: Option<&str>) -> Option<String> {
    let header = accept_language?;
    for item in header.split(',') {
        let primary = item
            .split(';')
            .next()
            .unwrap_or("")
            .trim()
            .split('-')
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();
        if !primary.is_empty() && CATALOGS.iter().any(|(loc, _)| *loc == primary) {
            return Some(primary);
        }
    }
    None
}

fn lookup(catalogs: &[(&str, &[(&str, &str)])], locale: &str, msgid: &str) -> Option<String> {
    catalogs
        .iter()
        .find(|(loc, _)| *loc == locale)
        .and_then(|(_, entries)| entries.iter().find(|(id, _)| *id == msgid))
        .map(|(_, s)| s.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    const CAT: &[(&str, &[(&str, &str)])] = &[("fi", &[("Sign in", "Kirjaudu sisään")])];

    #[test]
    fn lookup_hit_and_misses_fall_back() {
        assert_eq!(
            lookup(CAT, "fi", "Sign in").as_deref(),
            Some("Kirjaudu sisään")
        );
        assert_eq!(lookup(CAT, "fi", "Unknown"), None); // unknown msgid
        assert_eq!(lookup(CAT, "de", "Sign in"), None); // locale not in catalog
    }

    #[test]
    fn best_locale_matches_only_compiled_catalogs() {
        // Negotiation returns a locale only when a compiled catalog (fi/fr/zh) matches; None
        // otherwise, leaving the fallback to the caller.
        assert_eq!(best_locale(None), None);
        assert_eq!(best_locale(Some("de-DE,de;q=0.9")), None);
        assert_eq!(best_locale(Some("fi-FI,fi;q=0.9")).as_deref(), Some("fi"));
    }
}
