//! gettext-style i18n: po/<locale>.po compiled by build.rs into a static lookup (no runtime
//! files); msgid = the English source string; a missing entry falls back to the source.
//! Locale comes from Accept-Language (no per-user preference storage in v1).

// Generated by build.rs: `pub static CATALOGS: &[(&str, &[(&str, &str)])]`.
include!(concat!(env!("OUT_DIR"), "/i18n_catalog.rs"));

/// Translate `msgid` into `locale` (a primary subtag like "fi"); English source on any miss.
pub fn tr(locale: &str, msgid: &str) -> String {
    lookup(CATALOGS, locale, msgid).unwrap_or_else(|| msgid.to_string())
}

/// Best available locale for an Accept-Language value: primary subtags only, q-values ignored
/// (header order is preference enough). Matches against compiled catalogs; falls back to "en".
pub fn best_locale(accept_language: Option<&str>) -> String {
    let Some(header) = accept_language else {
        return "en".to_string();
    };
    for item in header.split(',') {
        let primary = item
            .split(';')
            .next()
            .unwrap_or("")
            .trim()
            .split('-')
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();
        if !primary.is_empty() && CATALOGS.iter().any(|(loc, _)| *loc == primary) {
            return primary;
        }
    }
    "en".to_string()
}

fn lookup(catalogs: &[(&str, &[(&str, &str)])], locale: &str, msgid: &str) -> Option<String> {
    catalogs
        .iter()
        .find(|(loc, _)| *loc == locale)
        .and_then(|(_, entries)| entries.iter().find(|(id, _)| *id == msgid))
        .map(|(_, s)| s.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    const CAT: &[(&str, &[(&str, &str)])] = &[("fi", &[("Sign in", "Kirjaudu sisään")])];

    #[test]
    fn lookup_hit_and_misses_fall_back() {
        assert_eq!(
            lookup(CAT, "fi", "Sign in").as_deref(),
            Some("Kirjaudu sisään")
        );
        assert_eq!(lookup(CAT, "fi", "Unknown"), None); // unknown msgid
        assert_eq!(lookup(CAT, "de", "Sign in"), None); // locale not in catalog
    }

    #[test]
    fn best_locale_defaults_to_en() {
        // Negotiation only returns locales present in the compiled catalogs; English otherwise.
        assert_eq!(best_locale(None), "en");
        assert_eq!(best_locale(Some("de-DE,de;q=0.9")), "en");
    }
}
