//! gettext-style i18n: po/<locale>.po compiled by build.rs into a static lookup (no runtime
//! files); msgid = the English source string; a missing entry falls back to the source.
//! Locale negotiation lives in the web layer (`lang_of`): the browser's Accept-Language (when
//! `http_accept_language` is on) else the `default_lang` CEL expression.

// Generated by build.rs: `pub static CATALOGS: &[(&str, &[(&str, &str)])]`.
include!(concat!(env!("OUT_DIR"), "/i18n_catalog.rs"));

/// Translate `msgid` into `locale` (a primary subtag like "fi"); English source on any miss.
pub fn tr(locale: &str, msgid: &str) -> String {
    lookup(CATALOGS, locale, msgid).unwrap_or_else(|| msgid.to_string())
}

/// Translate a `{count}`-templated `msgid` and substitute the number. Single plural form: the
/// translation must read naturally for any count (e.g. Finnish partitive "käyttäjää"), so there is
/// no n=1 special case — see the TRANSLATORS note on the string in the .po files.
pub fn tr_count(locale: &str, msgid: &str, count: usize) -> String {
    tr(locale, msgid).replace("{count}", &count.to_string())
}

/// The browser's most-preferred UI locale we can serve: the first primary subtag (in header order,
/// q-values ignored) matching a compiled catalog OR `en`, the source language. `en` must count as
/// serveable even though it has no catalog — otherwise the walk skips a higher-priority English
/// entry and matches a lower-priority translation (e.g. `en-GB,en;q=0.9,fi;q=0.8` → wrongly `fi`).
/// `None` when there's no header or nothing serveable — the caller (`lang_of`) decides the fallback.
pub fn best_locale(accept_language: Option<&str>) -> Option<String> {
    let header = accept_language?;
    for item in header.split(',') {
        let primary = item
            .split(';')
            .next()
            .unwrap_or("")
            .trim()
            .split('-')
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();
        if !primary.is_empty()
            && (primary == "en" || CATALOGS.iter().any(|(loc, _)| *loc == primary))
        {
            return Some(primary);
        }
    }
    None
}

fn lookup(catalogs: &[(&str, &[(&str, &str)])], locale: &str, msgid: &str) -> Option<String> {
    catalogs
        .iter()
        .find(|(loc, _)| *loc == locale)
        .and_then(|(_, entries)| entries.iter().find(|(id, _)| *id == msgid))
        .map(|(_, s)| s.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    const CAT: &[(&str, &[(&str, &str)])] = &[("fi", &[("Sign in", "Kirjaudu sisään")])];

    #[test]
    fn lookup_hit_and_misses_fall_back() {
        assert_eq!(
            lookup(CAT, "fi", "Sign in").as_deref(),
            Some("Kirjaudu sisään")
        );
        assert_eq!(lookup(CAT, "fi", "Unknown"), None); // unknown msgid
        assert_eq!(lookup(CAT, "de", "Sign in"), None); // locale not in catalog
    }

    #[test]
    fn best_locale_matches_catalog_or_english_source() {
        // Negotiation returns a locale for a compiled catalog (fi/fr/zh) or English (the source);
        // None otherwise, leaving the fallback to the caller.
        assert_eq!(best_locale(None), None);
        assert_eq!(best_locale(Some("de-DE,de;q=0.9")), None);
        assert_eq!(best_locale(Some("fi-FI,fi;q=0.9")).as_deref(), Some("fi"));
        // English is serveable (source language), so a higher-priority "en" beats a lower-priority
        // translated catalog instead of being skipped over.
        assert_eq!(
            best_locale(Some("en-GB,en;q=0.9,fi;q=0.8,en-US;q=0.7")).as_deref(),
            Some("en")
        );
    }
}
